version: '3'
services:
  app:
    build: .

  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: employees
    restart: always
    ports:
    - "33060:3306"
